name: Build, lint and test

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check tools
      run: |
        shellcheck --version
        autoreconf --version
        make --version
    - uses: actions/checkout@v3
    - name: lint shell files
      run: ./lint.sh
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
